
language: python

python:
  - "3.6.7"

install:
  - pip install -r requirements.txt
  - pipenv install
  - pip install coverage 
  - pip install codecov

services:
  - postgresql

addons:
  postgres: "9.5"
  
before_script:
  - psql -c "CREATE DATABASE ireportertest" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres

script:
  - pytest --cov-report term-missing --cov=app

after_script:
  - coveralls

after_success:
  - codecov
  - coveralls 